import { Question } from "./types";

export const questions: Question[] = [
  {
    id: "name",
    type: "open",
    section: "Nombre completo",
    prompt: "Ingresa tu nombre",
    placeholder: "Nombre por favor"
  },
  {
    id: "satisfaccion_general",
    type: "rating",
    section: "Experiencia general",
    prompt: "¿Qué tan satisfecho te sientes con tu experiencia en el ministerio?",
    scale: 10,
    lowLabel: "Nada satisfecho",
    highLabel: "Muy satisfecho",
  },
  {
    id: "lo_que_disfruta",
    type: "open",
    section: "Experiencia general",
    prompt: "¿Qué es lo que más disfrutas de participar en el ministerio?",
    placeholder: "Escribe tu respuesta aquí...",
  },
  {
    id: "sentirse_valorado",
    type: "choice",
    section: "Experiencia general",
    prompt: "¿Sientes que tu trabajo o aportación es valorado dentro del equipo?",
    options: ["Sí, totalmente", "Más o menos", "No mucho", "No"],
  },
  {
    id: "comunicacion",
    type: "choice",
    section: "Organización y comunicación",
    prompt: "¿Cómo calificarías la comunicación dentro del equipo?",
    options: ["Muy clara", "Clara", "Regular", "Confusa"],
  },
  {
    id: "distribucion_tareas",
    type: "choice",
    section: "Organización y comunicación",
    prompt: "¿Sientes que las tareas y responsabilidades están bien distribuidas?",
    options: ["Sí", "Parcialmente", "No"],
  },
  {
    id: "tiempo_info",
    type: "choice",
    section: "Organización y comunicación",
    prompt: "¿Recibiste el tiempo y la información necesaria para cumplir con tus tareas?",
    options: ["Siempre", "La mayoría de veces", "Pocas veces", "Casi nunca"],
  },
  {
    id: "aprendizaje",
    type: "choice",
    section: "Crecimiento y capacitación",
    prompt: "¿Sientes que has aprendido o mejorado tus habilidades estando en el ministerio?",
    options: ["Sí, bastante", "Un poco", "No mucho", "No"],
  },
  {
    id: "capacitacion_deseada",
    type: "open",
    section: "Crecimiento y capacitación",
    prompt: "¿Te gustaría recibir alguna capacitación o taller específico? ¿Cuál?",
    placeholder: "Ej. edición de video, fotografía, diseño gráfico...",
    optional: true,
  },
  {
    id: "menos_gustado",
    type: "open",
    section: "Áreas de mejora",
    prompt: "¿Qué es lo que menos te ha gustado o lo que más se te ha dificultado?",
    placeholder: "Escribe tu respuesta aquí...",
  },
  {
    id: "un_cambio",
    type: "open",
    section: "Áreas de mejora",
    prompt: "Si pudieras cambiar una sola cosa del ministerio, ¿qué sería?",
    placeholder: "Escribe tu respuesta aquí...",
  },
  {
    id: "recursos_faltantes",
    type: "open",
    section: "Áreas de mejora",
    prompt: "¿Qué recursos, herramientas o apoyo sientes que nos hace falta?",
    placeholder: "Escribe tu respuesta aquí...",
    optional: true,
  },
  {
    id: "comentario_libre",
    type: "open",
    section: "Cierre",
    prompt: "¿Algo más que quieras compartir o sugerir?",
    placeholder: "Comentario libre (opcional)",
    optional: true,
  },
  {
    id: "campamento",
    type: "open",
    section: "Campamento",
    prompt: "¿Cómo viste la organización del ministerio durante campamento?",
    placeholder: "Comentario libre",
  },
  {
    id: "otras_actividades",
    type: "open",
    section: "Varios",
    prompt: "¿Hay algo nuevo que deseas agregar?",
    placeholder: "Comentario libre",
  },
  {
    id: "caer_mal",
    type: "open",
    section: "Varios",
    prompt: "Quién te cae mal del grupo?",
    placeholder: "Comentario libre (opcional)",
    optional: true,
  },
];